name: Pre-commit Cache Warm-up

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  warm-pre-commit-cache:
    uses: leinardi/gh-reusable-workflows/.github/workflows/pre-commit-warmup.yaml@4b8d094239089d9f91fd15b929db30fcb2a3c118 # v1.3.1
